//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package org.twc.minijavacompiler.zmipssyntaxtree;

/**
 * Grammar production:
 * f0 -> "print"
 * f1 -> SimpleExp()
 */
public class PrintStmt implements Node {
   public NodeToken f0;
   public SimpleExp f1;

   public PrintStmt(NodeToken n0, SimpleExp n1) {
      f0 = n0;
      f1 = n1;
   }

   public PrintStmt(SimpleExp n0) {
      f0 = new NodeToken("print");
      f1 = n0;
   }

   public void accept(org.twc.minijavacompiler.zmipsvisitor.Visitor v) throws Exception {
      v.visit(this);
   }
   public <R,A> R accept(org.twc.minijavacompiler.zmipsvisitor.GJVisitor<R,A> v, A argu) throws Exception {
      return v.visit(this,argu);
   }
   public <R> R accept(org.twc.minijavacompiler.zmipsvisitor.GJNoArguVisitor<R> v) throws Exception {
      return v.visit(this);
   }
   public <A> void accept(org.twc.minijavacompiler.zmipsvisitor.GJVoidVisitor<A> v, A argu) throws Exception {
      v.visit(this,argu);
   }
}

