//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package org.twc.minijavacompiler.zmipsvisitor;
import org.twc.minijavacompiler.zmipssyntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) throws Exception {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeListOptional n) throws Exception {
      if ( n.present() )
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
   }

   public void visit(NodeOptional n) throws Exception {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) throws Exception {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeToken n) throws Exception {}

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ZMIPSProg()
    * f1 -> <EOF>
    */
   public void visit(Goal n) throws Exception {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ( Stmt() )*
    */
   public void visit(ZMIPSProg n) throws Exception {
      n.f0.accept(this);
   }

   /**
    * f0 -> Label()
    *       | TwoRegInstr()
    *       | ThreeRegInstr()
    *       | JmpStmts()
    *       | ComparisonStmts()
    *       | LwStmt()
    *       | SwStmt()
    *       | PrintStmt()
    *       | AnswerStmt()
    *       | PubReadStmt()
    *       | SecReadStmt()
    */
   public void visit(Stmt n) throws Exception {
      n.f0.accept(this);
   }

   /**
    * f0 -> JmpOps()
    * f1 -> Label()
    */
   public void visit(JmpStmts n) throws Exception {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "j"
    *       | "cjmp"
    *       | "cnjmp"
    */
   public void visit(JmpOps n) throws Exception {
      n.f0.accept(this);
   }

   /**
    * f0 -> ComparisonOps()
    * f1 -> Register()
    * f2 -> ","
    * f3 -> SimpleExp()
    */
   public void visit(ComparisonStmts n) throws Exception {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> "cmpe"
    *       | "cmpg"
    *       | "cmpge"
    */
   public void visit(ComparisonOps n) throws Exception {
      n.f0.accept(this);
   }

   /**
    * f0 -> "lw"
    * f1 -> ","
    * f2 -> SimpleExp()
    * f3 -> "("
    * f4 -> SimpleExp()
    * f5 -> ")"
    */
   public void visit(LwStmt n) throws Exception {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> "sw"
    * f1 -> ","
    * f2 -> SimpleExp()
    * f3 -> "("
    * f4 -> SimpleExp()
    * f5 -> ")"
    */
   public void visit(SwStmt n) throws Exception {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> TwoRegInstrOp()
    * f1 -> Register()
    * f2 -> ","
    * f3 -> SimpleExp()
    */
   public void visit(TwoRegInstr n) throws Exception {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> "move"
    *       | "la"
    *       | "not"
    */
   public void visit(TwoRegInstrOp n) throws Exception {
      n.f0.accept(this);
   }

   /**
    * f0 -> ThreeRegInstrOp()
    * f1 -> Register()
    * f2 -> ","
    * f3 -> Register()
    * f4 -> ","
    * f5 -> SimpleExp()
    */
   public void visit(ThreeRegInstr n) throws Exception {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> "and"
    *       | "or"
    *       | "xor"
    *       | "add"
    *       | "sub"
    *       | "mult"
    *       | "sll"
    *       | "srl"
    */
   public void visit(ThreeRegInstrOp n) throws Exception {
      n.f0.accept(this);
   }

   /**
    * f0 -> "print"
    * f1 -> SimpleExp()
    */
   public void visit(PrintStmt n) throws Exception {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "answer"
    * f1 -> SimpleExp()
    */
   public void visit(AnswerStmt n) throws Exception {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "pubread"
    * f1 -> Register()
    */
   public void visit(PubReadStmt n) throws Exception {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "secread"
    * f1 -> Register()
    */
   public void visit(SecReadStmt n) throws Exception {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Register()
    *       | IntegerLiteral()
    *       | Label()
    */
   public void visit(SimpleExp n) throws Exception {
      n.f0.accept(this);
   }

   /**
    * f0 -> <REGISTER>
    */
   public void visit(Register n) throws Exception {
      n.f0.accept(this);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public void visit(IntegerLiteral n) throws Exception {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public void visit(Label n) throws Exception {
      n.f0.accept(this);
   }

}
