//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package org.twc.minijavacompiler.zmipsvisitor;
import org.twc.minijavacompiler.zmipssyntaxtree.*;
import java.util.*;

/**
 * All GJ visitors with no argument must implement this interface.
 */

public interface GJNoArguVisitor<R> {

   //
   // GJ Auto class visitors with no argument
   //

   public R visit(NodeList n)  throws Exception;
   public R visit(NodeListOptional n)  throws Exception;
   public R visit(NodeOptional n)  throws Exception;
   public R visit(NodeSequence n)  throws Exception;
   public R visit(NodeToken n)  throws Exception;

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ZMIPSProg()
    * f1 -> <EOF>
    */
   public R visit(Goal n) throws Exception;

   /**
    * f0 -> ( Stmt() )*
    */
   public R visit(ZMIPSProg n) throws Exception;

   /**
    * f0 -> Label()
    *       | TwoRegInstr()
    *       | ThreeRegInstr()
    *       | JmpStmts()
    *       | ComparisonStmts()
    *       | LwStmt()
    *       | SwStmt()
    *       | PrintStmt()
    *       | AnswerStmt()
    *       | PubReadStmt()
    *       | SecReadStmt()
    */
   public R visit(Stmt n) throws Exception;

   /**
    * f0 -> JmpOps()
    * f1 -> Label()
    */
   public R visit(JmpStmts n) throws Exception;

   /**
    * f0 -> "j"
    *       | "cjmp"
    *       | "cnjmp"
    */
   public R visit(JmpOps n) throws Exception;

   /**
    * f0 -> ComparisonOps()
    * f1 -> Register()
    * f2 -> ","
    * f3 -> SimpleExp()
    */
   public R visit(ComparisonStmts n) throws Exception;

   /**
    * f0 -> "cmpe"
    *       | "cmpg"
    *       | "cmpge"
    */
   public R visit(ComparisonOps n) throws Exception;

   /**
    * f0 -> "lw"
    * f1 -> ","
    * f2 -> SimpleExp()
    * f3 -> "("
    * f4 -> SimpleExp()
    * f5 -> ")"
    */
   public R visit(LwStmt n) throws Exception;

   /**
    * f0 -> "sw"
    * f1 -> ","
    * f2 -> SimpleExp()
    * f3 -> "("
    * f4 -> SimpleExp()
    * f5 -> ")"
    */
   public R visit(SwStmt n) throws Exception;

   /**
    * f0 -> TwoRegInstrOp()
    * f1 -> Register()
    * f2 -> ","
    * f3 -> SimpleExp()
    */
   public R visit(TwoRegInstr n) throws Exception;

   /**
    * f0 -> "move"
    *       | "la"
    *       | "not"
    */
   public R visit(TwoRegInstrOp n) throws Exception;

   /**
    * f0 -> ThreeRegInstrOp()
    * f1 -> Register()
    * f2 -> ","
    * f3 -> Register()
    * f4 -> ","
    * f5 -> SimpleExp()
    */
   public R visit(ThreeRegInstr n) throws Exception;

   /**
    * f0 -> "and"
    *       | "or"
    *       | "xor"
    *       | "add"
    *       | "sub"
    *       | "mult"
    *       | "sll"
    *       | "srl"
    */
   public R visit(ThreeRegInstrOp n) throws Exception;

   /**
    * f0 -> "print"
    * f1 -> SimpleExp()
    */
   public R visit(PrintStmt n) throws Exception;

   /**
    * f0 -> "answer"
    * f1 -> SimpleExp()
    */
   public R visit(AnswerStmt n) throws Exception;

   /**
    * f0 -> "pubread"
    * f1 -> Register()
    */
   public R visit(PubReadStmt n) throws Exception;

   /**
    * f0 -> "secread"
    * f1 -> Register()
    */
   public R visit(SecReadStmt n) throws Exception;

   /**
    * f0 -> Register()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(SimpleExp n) throws Exception;

   /**
    * f0 -> <REGISTER>
    */
   public R visit(Register n) throws Exception;

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n) throws Exception;

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n) throws Exception;

}

