//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package org.twc.minijavacompiler.zmipsvisitor;
import org.twc.minijavacompiler.zmipssyntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJVoidDepthFirst<A> implements GJVoidVisitor<A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n, A argu) throws Exception {
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
   }

   public void visit(NodeListOptional n, A argu) throws Exception {
      if ( n.present() ) {
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
      }
   }

   public void visit(NodeOptional n, A argu) throws Exception {
      if ( n.present() )
         n.node.accept(this,argu);
   }

   public void visit(NodeSequence n, A argu) throws Exception {
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
   }

   public void visit(NodeToken n, A argu) throws Exception {}

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ZMIPSProg()
    * f1 -> <EOF>
    */
   public void visit(Goal n, A argu) throws Exception {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> ( Stmt() )*
    */
   public void visit(ZMIPSProg n, A argu) throws Exception {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> Label()
    *       | TwoRegInstr()
    *       | ThreeRegInstr()
    *       | JmpStmts()
    *       | ComparisonStmts()
    *       | LwStmt()
    *       | SwStmt()
    *       | PrintStmt()
    *       | AnswerStmt()
    *       | PubReadStmt()
    *       | SecReadStmt()
    */
   public void visit(Stmt n, A argu) throws Exception {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> JmpOps()
    * f1 -> Label()
    */
   public void visit(JmpStmts n, A argu) throws Exception {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> "j"
    *       | "cjmp"
    *       | "cnjmp"
    */
   public void visit(JmpOps n, A argu) throws Exception {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> ComparisonOps()
    * f1 -> Register()
    * f2 -> ","
    * f3 -> SimpleExp()
    */
   public void visit(ComparisonStmts n, A argu) throws Exception {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
   }

   /**
    * f0 -> "cmpe"
    *       | "cmpg"
    *       | "cmpge"
    */
   public void visit(ComparisonOps n, A argu) throws Exception {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> "lw"
    * f1 -> ","
    * f2 -> SimpleExp()
    * f3 -> "("
    * f4 -> SimpleExp()
    * f5 -> ")"
    */
   public void visit(LwStmt n, A argu) throws Exception {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
   }

   /**
    * f0 -> "sw"
    * f1 -> ","
    * f2 -> SimpleExp()
    * f3 -> "("
    * f4 -> SimpleExp()
    * f5 -> ")"
    */
   public void visit(SwStmt n, A argu) throws Exception {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
   }

   /**
    * f0 -> TwoRegInstrOp()
    * f1 -> Register()
    * f2 -> ","
    * f3 -> SimpleExp()
    */
   public void visit(TwoRegInstr n, A argu) throws Exception {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
   }

   /**
    * f0 -> "move"
    *       | "la"
    *       | "not"
    */
   public void visit(TwoRegInstrOp n, A argu) throws Exception {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> ThreeRegInstrOp()
    * f1 -> Register()
    * f2 -> ","
    * f3 -> Register()
    * f4 -> ","
    * f5 -> SimpleExp()
    */
   public void visit(ThreeRegInstr n, A argu) throws Exception {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
   }

   /**
    * f0 -> "and"
    *       | "or"
    *       | "xor"
    *       | "add"
    *       | "sub"
    *       | "mult"
    *       | "sll"
    *       | "srl"
    */
   public void visit(ThreeRegInstrOp n, A argu) throws Exception {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> "print"
    * f1 -> SimpleExp()
    */
   public void visit(PrintStmt n, A argu) throws Exception {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> "answer"
    * f1 -> SimpleExp()
    */
   public void visit(AnswerStmt n, A argu) throws Exception {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> "pubread"
    * f1 -> Register()
    */
   public void visit(PubReadStmt n, A argu) throws Exception {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> "secread"
    * f1 -> Register()
    */
   public void visit(SecReadStmt n, A argu) throws Exception {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> Register()
    *       | IntegerLiteral()
    *       | Label()
    */
   public void visit(SimpleExp n, A argu) throws Exception {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> <REGISTER>
    */
   public void visit(Register n, A argu) throws Exception {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public void visit(IntegerLiteral n, A argu) throws Exception {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public void visit(Label n, A argu) throws Exception {
      n.f0.accept(this, argu);
   }

}
