//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ( MethodDeclaration() )*
 * f1 -> MainMethodDeclaration()
 * f2 -> <EOF>
 */
public class Goal implements Node {
   public NodeListOptional f0;
   public MainMethodDeclaration f1;
   public NodeToken f2;

   public Goal(NodeListOptional n0, MainMethodDeclaration n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public Goal(NodeListOptional n0, MainMethodDeclaration n1) {
      f0 = n0;
      f1 = n1;
      f2 = new NodeToken("");
   }

   public void accept(visitor.Visitor v) throws Exception {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) throws Exception {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) throws Exception {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) throws Exception {
      v.visit(this,argu);
   }
}

