#!/bin/bash

printf "\033[1;33m _______ _      _     \033[0m  _____                       _ _           \n"
printf "\033[1;33m|___  (_) |    | |    \033[0m /  __ \                     (_) |          \n"
printf "\033[1;33m   / / _| | ___| |__  \033[0m | /  \/ ___  _ __ ___  _ __  _| | ___ _ __ \n"
printf "\033[1;33m  / / | | |/ __| '_ \ \033[0m | |    / _ \| '_   _ \| '_ \| | |/ _ \ '__|\n"
printf "\033[1;33m./ /__| | | (__| | | |\033[0m | \__/\ (_) | | | | | | |_) | | |  __/ |   \n"
printf "\033[1;33m\_____/_|_|\___|_| |_|\033[0m  \____/\___/|_| |_| |_| .__/|_|_|\___|_|   \n"
printf "\033[1;33m                      \033[0m                       | |                  \n"
printf "\033[1;33m                      \033[0m                       |_|                  \n"
echo ""

JVM="java"
CLASSPATH="lib/iris-0.60.jar:lib/iris-parser-0.60.jar:."

if [ "$#" -ne 1 ] && { [ "$#" -ne 2 ] || [ "$2" != "-opts" ]; }  then
    printf "\033[0;33mUsage: \033[0;32m./zc\033[0m path-to-zl-file [-opts]\n"
    printf "\n"
    printf "The -opts flag enables optimizations on the generated assembly code. Use cautiously.\n"
    printf "\n"
    exit -1
fi

inputfile=$(pwd)/$1
cd ./compiler/src/zilch/
ASM="$($JVM Main $inputfile | sed -n 1p)"
RES=$ASM
cd ../../../

if [ "$2" == "-opts" ]; then
    cd ./optimizer/src/zilch/
    OPT="$($JVM -cp $CLASSPATH Main $ASM | sed -n 1p)"
    # Do optimizations util reaching a fixed point
    DIFF=$(diff $ASM $OPT)
    while [[ "$DIFF" != "" ]] ; do
        mv $OPT $ASM
        OPT="$($JVM -cp $CLASSPATH Main $ASM | sed -n 1p)"
        DIFF=$(diff $ASM $OPT)
    done
    ASM=$OPT
fi

if [ "$ASM" != "$RES" ]; then
    mv $ASM $RES
fi

echo -e "zMIPS output:" $RES "\n"
cat $RES
