#!/bin/bash

printf "\033[1;33m _______ _      _     \033[0m  _____      _                           _\n"
printf "\033[1;33m|___  (_) |    | |    \033[0m |_   _|    | |                         | |\n"
printf "\033[1;33m   / / _| | ___| |__  \033[0m   | | _ __ | |_ ___ _ __ _ __  _ __ ___| |_ ___ _ __\n"
printf "\033[1;33m  / / | | |/ __| '_ \ \033[0m   | || '_ \| __/ _ \ '__| '_ \| '__/ _ \ __/ _ \ '__|\n"
printf "\033[1;33m./ /__| | | (__| | | |\033[0m  _| || | | | ||  __/ |  | |_) | | |  __/ ||  __/ |\n"
printf "\033[1;33m\_____/_|_|\___|_| |_|\033[0m  \___/_| |_|\__\___|_|  | .__/|_|  \___|\__\___|_|\n"
printf "\033[1;33m                      \033[0m                         | |\n"
printf "\033[1;33m                      \033[0m                         |_|\n"
echo ""


if [ "$#" -ne 1 ] && { [ "$#" -ne 2 ] || [ "$2" != "-opts" ]; }  then
    printf "\033[0;33mUsage: \033[0;32m./zi\033[0m path-to-zl-file [public-tape] [private-tape]\n"
    printf "\n"
    printf "If the public tape is in the sam directory under the same name as the .zl file and with an extension .pubtape, it can be ommitted and will fetched automatically.\n"
    printf "\n"
    exit -1
fi

inputfile=$(pwd)/$1
filename=${inputfile::-3}
publictape=$filename.pubtape
privatetape=$filename.auxtape
if test -f "$publictape"; then
    if test -f "$privatetape"; then
        echo $(python ./interpreter/zi.py --filename $inputfile --pubtape $publictape --auxtape $privatetape)
    else
        echo $(python ./interpreter/zi.py --filename $inputfile --pubtape $publictape)
    fi
elif test -f "$privatetape"; then
    echo $(python ./interpreter/zi.py --filename $inputfile --auxtape $publictape)
else
    echo $(python ./interpreter/zi.py --filename $inputfile)
fi
