//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package org.twc.minijavacompiler.syntaxtree;

/**
 * Grammar production:
 * f0 -> AndExpression()
 *       | OrExpression()
 *       | BinAndExpression()
 *       | BinOrExpression()
 *       | BinXorExpression()
 *       | BinNotExpression()
 *       | ShiftLeftExpression()
 *       | ShiftRightExpression()
 *       | EqualExpression()
 *       | NotEqualExpression()
 *       | LessThanExpression()
 *       | LessThanOrEqualExpression()
 *       | GreaterThanExpression()
 *       | GreaterThanOrEqualExpression()
 *       | PlusExpression()
 *       | MinusExpression()
 *       | TimesExpression()
 *       | DivExpression()
 *       | ArrayLookup()
 *       | ArrayLength()
 *       | MessageSend()
 *       | TernaryExpression()
 *       | PublicReadExpression()
 *       | PrivateReadExpression()
 *       | Clause()
 */
public class Expression implements Node {
   public NodeChoice f0;

   public Expression(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(org.twc.minijavacompiler.visitor.Visitor v) throws Exception {
      v.visit(this);
   }
   public <R,A> R accept(org.twc.minijavacompiler.visitor.GJVisitor<R,A> v, A argu) throws Exception {
      return v.visit(this,argu);
   }
   public <R> R accept(org.twc.minijavacompiler.visitor.GJNoArguVisitor<R> v) throws Exception {
      return v.visit(this);
   }
   public <A> void accept(org.twc.minijavacompiler.visitor.GJVoidVisitor<A> v, A argu) throws Exception {
      v.visit(this,argu);
   }
}

