//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package org.twc.minijavacompiler.syntaxtree;

/**
 * Grammar production:
 * f0 -> "("
 * f1 -> Expression()
 * f2 -> ")"
 * f3 -> "?"
 * f4 -> Expression()
 * f5 -> ":"
 * f6 -> Expression()
 */
public class TernaryExpression implements Node {
   public NodeToken f0;
   public Expression f1;
   public NodeToken f2;
   public NodeToken f3;
   public Expression f4;
   public NodeToken f5;
   public Expression f6;

   public TernaryExpression(NodeToken n0, Expression n1, NodeToken n2, NodeToken n3, Expression n4, NodeToken n5, Expression n6) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
   }

   public TernaryExpression(Expression n0, Expression n1, Expression n2) {
      f0 = new NodeToken("(");
      f1 = n0;
      f2 = new NodeToken(")");
      f3 = new NodeToken("?");
      f4 = n1;
      f5 = new NodeToken(":");
      f6 = n2;
   }

   public void accept(org.twc.minijavacompiler.visitor.Visitor v) throws Exception {
      v.visit(this);
   }
   public <R,A> R accept(org.twc.minijavacompiler.visitor.GJVisitor<R,A> v, A argu) throws Exception {
      return v.visit(this,argu);
   }
   public <R> R accept(org.twc.minijavacompiler.visitor.GJNoArguVisitor<R> v) throws Exception {
      return v.visit(this);
   }
   public <A> void accept(org.twc.minijavacompiler.visitor.GJVoidVisitor<A> v, A argu) throws Exception {
      v.visit(this,argu);
   }
}

