//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ void visitors must implement this interface.
 */

public interface GJVoidVisitor<A> {

   //
   // GJ void Auto class visitors
   //

   public void visit(NodeList n, A argu) throws Exception;
   public void visit(NodeListOptional n, A argu) throws Exception;
   public void visit(NodeOptional n, A argu) throws Exception;
   public void visit(NodeSequence n, A argu) throws Exception;
   public void visit(NodeToken n, A argu) throws Exception;

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( MethodDeclaration() )*
    * f1 -> MainMethodDeclaration()
    * f2 -> <EOF>
    */
   public void visit(Goal n, A argu) throws Exception;

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public void visit(VarDeclaration n, A argu) throws Exception;

   /**
    * f0 -> "void"
    * f1 -> "main"
    * f2 -> "("
    * f3 -> "void"
    * f4 -> ")"
    * f5 -> "{"
    * f6 -> ( VarDeclaration() )*
    * f7 -> ( Statement() )*
    * f8 -> "}"
    */
   public void visit(MainMethodDeclaration n, A argu) throws Exception;

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ( FormalParameterList() )?
    * f4 -> ")"
    * f5 -> "{"
    * f6 -> ( VarDeclaration() )*
    * f7 -> ( Statement() )*
    * f8 -> "return"
    * f9 -> Expression()
    * f10 -> ";"
    * f11 -> "}"
    */
   public void visit(MethodDeclaration n, A argu) throws Exception;

   /**
    * f0 -> FormalParameter()
    * f1 -> FormalParameterTail()
    */
   public void visit(FormalParameterList n, A argu) throws Exception;

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public void visit(FormalParameter n, A argu) throws Exception;

   /**
    * f0 -> ( FormalParameterTerm() )*
    */
   public void visit(FormalParameterTail n, A argu) throws Exception;

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public void visit(FormalParameterTerm n, A argu) throws Exception;

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public void visit(Type n, A argu) throws Exception;

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public void visit(ArrayType n, A argu) throws Exception;

   /**
    * f0 -> "boolean"
    */
   public void visit(BooleanType n, A argu) throws Exception;

   /**
    * f0 -> "int"
    */
   public void visit(IntegerType n, A argu) throws Exception;

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | PlusPlusExpression()
    *       | MinusMinusExpression()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    *       | ReadPrimaryTape()
    *       | ReadPrivateTape()
    *       | SeekPrimaryTape()
    *       | SeekPrivateTape()
    *       | AnswerStatement()
    */
   public void visit(Statement n, A argu) throws Exception;

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public void visit(Block n, A argu) throws Exception;

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public void visit(AssignmentStatement n, A argu) throws Exception;

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public void visit(ArrayAssignmentStatement n, A argu) throws Exception;

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public void visit(IfStatement n, A argu) throws Exception;

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public void visit(WhileStatement n, A argu) throws Exception;

   /**
    * f0 -> "Out.print"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public void visit(PrintStatement n, A argu) throws Exception;

   /**
    * f0 -> "PrimaryTape.read"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public void visit(ReadPrimaryTape n, A argu) throws Exception;

   /**
    * f0 -> "PrivateTape.read"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public void visit(ReadPrivateTape n, A argu) throws Exception;

   /**
    * f0 -> "PrimaryTape.seek"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ","
    * f4 -> Expression()
    * f5 -> ")"
    * f6 -> ";"
    */
   public void visit(SeekPrimaryTape n, A argu) throws Exception;

   /**
    * f0 -> "PrivateTape.seek"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ","
    * f4 -> Expression()
    * f5 -> ")"
    * f6 -> ";"
    */
   public void visit(SeekPrivateTape n, A argu) throws Exception;

   /**
    * f0 -> "Prover.answer"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public void visit(AnswerStatement n, A argu) throws Exception;

   /**
    * f0 -> AndExpression()
    *       | OrExpression()
    *       | EqExpression()
    *       | LessThanExpression()
    *       | GreaterThanExpression()
    *       | LessEqualThanExpression()
    *       | GreaterEqualThanExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | ArrayLookup()
    *       | MessageSend()
    *       | MethodCall()
    *       | Clause()
    */
   public void visit(Expression n, A argu) throws Exception;

   /**
    * f0 -> Clause()
    * f1 -> "&&"
    * f2 -> Clause()
    */
   public void visit(AndExpression n, A argu) throws Exception;

   /**
    * f0 -> Clause()
    * f1 -> "||"
    * f2 -> Clause()
    */
   public void visit(OrExpression n, A argu) throws Exception;

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "=="
    * f2 -> PrimaryExpression()
    */
   public void visit(EqExpression n, A argu) throws Exception;

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<"
    * f2 -> PrimaryExpression()
    */
   public void visit(LessThanExpression n, A argu) throws Exception;

   /**
    * f0 -> PrimaryExpression()
    * f1 -> ">"
    * f2 -> PrimaryExpression()
    */
   public void visit(GreaterThanExpression n, A argu) throws Exception;

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public void visit(LessEqualThanExpression n, A argu) throws Exception;

   /**
    * f0 -> PrimaryExpression()
    * f1 -> ">="
    * f2 -> PrimaryExpression()
    */
   public void visit(GreaterEqualThanExpression n, A argu) throws Exception;

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public void visit(PlusExpression n, A argu) throws Exception;

   /**
    * f0 -> Identifier()
    * f1 -> "++"
    * f2 -> ";"
    */
   public void visit(PlusPlusExpression n, A argu) throws Exception;

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public void visit(MinusExpression n, A argu) throws Exception;

   /**
    * f0 -> Identifier()
    * f1 -> "--"
    * f2 -> ";"
    */
   public void visit(MinusMinusExpression n, A argu) throws Exception;

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public void visit(TimesExpression n, A argu) throws Exception;

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public void visit(ArrayLookup n, A argu) throws Exception;

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public void visit(MessageSend n, A argu) throws Exception;

   /**
    * f0 -> Identifier()
    * f1 -> "("
    * f2 -> ( ExpressionList() )?
    * f3 -> ")"
    */
   public void visit(MethodCall n, A argu) throws Exception;

   /**
    * f0 -> Expression()
    * f1 -> ExpressionTail()
    */
   public void visit(ExpressionList n, A argu) throws Exception;

   /**
    * f0 -> ( ExpressionTerm() )*
    */
   public void visit(ExpressionTail n, A argu) throws Exception;

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public void visit(ExpressionTerm n, A argu) throws Exception;

   /**
    * f0 -> NotExpression()
    *       | PrimaryExpression()
    */
   public void visit(Clause n, A argu) throws Exception;

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ArrayAllocationExpression()
    *       | BracketExpression()
    */
   public void visit(PrimaryExpression n, A argu) throws Exception;

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public void visit(IntegerLiteral n, A argu) throws Exception;

   /**
    * f0 -> "true"
    */
   public void visit(TrueLiteral n, A argu) throws Exception;

   /**
    * f0 -> "false"
    */
   public void visit(FalseLiteral n, A argu) throws Exception;

   /**
    * f0 -> <IDENTIFIER>
    */
   public void visit(Identifier n, A argu) throws Exception;

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public void visit(ArrayAllocationExpression n, A argu) throws Exception;

   /**
    * f0 -> "!"
    * f1 -> Clause()
    */
   public void visit(NotExpression n, A argu) throws Exception;

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public void visit(BracketExpression n, A argu) throws Exception;

}

